In [2]:
##Task1
import numpy as np
array = np.array([2,4,6,8,10,12])

array_2 = array + 2
array_3 = array * 3
print(array_2)
print(array_3)

[ 4  6  8 10 12 14]
[ 6 12 18 24 30 36]


In [3]:
##Task2 
arr = np.array([1,2,3,6,4,5])
arr_rev = np.flip(arr)
print(arr_rev)

[5 4 6 3 2 1]


In [4]:
arr = np.array([1, 2, 2, 3, 3, 3, 4, 4, 4, 4])
counts = np.bincount(arr)
most_frequent_element = np.argmax(counts)
print(most_frequent_element)

4


In [7]:
#Task3
arr=np.array([[10, 20, 30], 
             [40, 50, 60], 
             [70, 80, 90]])
print(arr[0][1])
print(arr[2][0])

20
70


In [8]:
#Task4


# Creating a 1-D NumPy array named 'Ridhi' with 25 evenly spaced numbers from 10 to 100
Ridhi = np.linspace(10, 100, 25)

# Printing required properties
print("Array:", Ridhi)
print("Dimensions:", Ridhi.ndim) 
print("Shape:", Ridhi.shape) 
print("Total elements:", Ridhi.size) 
print("Data type of each element:", Ridhi.dtype)
print("Total bytes consumed:", Ridhi.nbytes)  

Ridhi_transposed = Ridhi.reshape(25, 1)
print("Transposed Array using reshape:\n", Ridhi_transposed)


print("Transpose using .T:\n", Ridhi.T)


print("Can we use T attribute? ", Ridhi.T.shape != Ridhi.shape)  # False, because T does nothing in 1D


Array: [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Dimensions: 1
Shape: (25,)
Total elements: 25
Data type of each element: float64
Total bytes consumed: 200
Transposed Array using reshape:
 [[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]
Transpose using .T:
 [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Can we use T attribute?  False
