In [1]:
import numpy as np

In [4]:
#Task1
gfg = np.matrix('[4, 1, 9], [12, 3, 1], [4, 5,6]')
print('Sum of all elements',gfg.sum())
print('Sum of elements row wise',np.sum(gfg,axis=1))
print('Sum of elements column wise',np.sum(gfg,axis=0))

Sum of all elements 45
Sum of elements row wise [[45]]
Sum of elements column wise [[ 4  1  9 12  3  1  4  5  6]]


In [5]:
#Task2 
array = np.array([10, 52, 62, 16, 16, 54, 453])
sort_array=np.sort(array)
print('Sorted array :',sort_array)
print('Indices of sorted array :',np.argsort(array))
print('4 smallest elements',sort_array[:4])
print('5 smallest elements',sort_array[-5:])

Sorted array : [ 10  16  16  52  54  62 453]
Indices of sorted array : [0 3 4 1 5 2 6]
4 smallest elements [10 16 16 52]
5 smallest elements [ 16  52  54  62 453]


In [6]:
#Task3
array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])
int_elements = array[array == np.floor(array)]
print('Integer elements :',int_elements)
float_elements = array[array != np.floor(array)]
print('Float elements :',float_elements)

Integer elements : [1. 2. 3. 2.]
Float elements : [1.2 2.2]


In [7]:
#Task4
#Name= Ridhi Gupta
X= ord('R')+ ord('G')
sales= np.array([X, X+50, X+100, X+150, X+200])
print(sales)

[153 203 253 303 353]


In [8]:
#Task5
tax_rate= ((X % 5)+5)/100
tax_sales= (tax_rate+1)*sales
print(tax_sales)

[165.24 219.24 273.24 327.24 381.24]


In [9]:
#Task6
discount_sales= np.where(sales<X+100, sales-sales*0.05, sales-sales*0.10)
print(discount_sales)

[145.35 192.85 227.7  272.7  317.7 ]


In [10]:
#Task7
week_sales= np.tile(sales,(3,1))
print('Broadcasted sales array :',week_sales)
weeks=np.arange(3)           #to separate rows
print('\n')
inc_sales=  week_sales * (1.02** weeks[:,np.newaxis])
print('Increased sales :\n',inc_sales)

Broadcasted sales array : [[153 203 253 303 353]
 [153 203 253 303 353]
 [153 203 253 303 353]]


Increased sales :
 [[153.     203.     253.     303.     353.    ]
 [156.06   207.06   258.06   309.06   360.06  ]
 [159.1812 211.2012 263.2212 315.2412 367.2612]]
